contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #taxtriage channel"
    url: https://nfcore.slack.com/channels/taxtriage
    about: Discussion about the nf-core/taxtriage pipeline
